/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderSlugRouteImport } from './routes/order.$slug'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders.index'
import { Route as AppInquiriesIndexRouteImport } from './routes/_app/inquiries.index'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products.$productId'
import { Route as AppOrdersPrintBatchRouteImport } from './routes/_app/orders.print-batch'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders.new'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app/orders.$orderId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers.$customerId'
import { Route as AppOrdersOrderIdWaybillRouteImport } from './routes/_app/orders.$orderId.waybill'
import { Route as AppOrdersOrderIdInvoiceRouteImport } from './routes/_app/orders.$orderId.invoice'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSlugRoute = OrderSlugRouteImport.update({
  id: '/order/$slug',
  path: '/order/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppInquiriesIndexRoute = AppInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersPrintBatchRoute = AppOrdersPrintBatchRouteImport.update({
  id: '/orders/print-batch',
  path: '/orders/print-batch',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppOrdersOrderIdWaybillRoute = AppOrdersOrderIdWaybillRouteImport.update({
  id: '/waybill',
  path: '/waybill',
  getParentRoute: () => AppOrdersOrderIdRoute,
} as any)
const AppOrdersOrderIdInvoiceRoute = AppOrdersOrderIdInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AppOrdersOrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/order/$slug': typeof OrderSlugRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRouteWithChildren
  '/orders/new': typeof AppOrdersNewRoute
  '/orders/print-batch': typeof AppOrdersPrintBatchRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/inquiries/': typeof AppInquiriesIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/orders/$orderId/invoice': typeof AppOrdersOrderIdInvoiceRoute
  '/orders/$orderId/waybill': typeof AppOrdersOrderIdWaybillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/order/$slug': typeof OrderSlugRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRouteWithChildren
  '/orders/new': typeof AppOrdersNewRoute
  '/orders/print-batch': typeof AppOrdersPrintBatchRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/inquiries': typeof AppInquiriesIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/orders/$orderId/invoice': typeof AppOrdersOrderIdInvoiceRoute
  '/orders/$orderId/waybill': typeof AppOrdersOrderIdWaybillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/order/$slug': typeof OrderSlugRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRouteWithChildren
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/orders/print-batch': typeof AppOrdersPrintBatchRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/inquiries/': typeof AppInquiriesIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/orders/$orderId/invoice': typeof AppOrdersOrderIdInvoiceRoute
  '/_app/orders/$orderId/waybill': typeof AppOrdersOrderIdWaybillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/order/$slug'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/orders/print-batch'
    | '/products/$productId'
    | '/inquiries/'
    | '/orders/'
    | '/products/'
    | '/orders/$orderId/invoice'
    | '/orders/$orderId/waybill'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/order/$slug'
    | '/customers/$customerId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/orders/print-batch'
    | '/products/$productId'
    | '/inquiries'
    | '/orders'
    | '/products'
    | '/orders/$orderId/invoice'
    | '/orders/$orderId/waybill'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_app/admin'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/reports'
    | '/_app/settings'
    | '/order/$slug'
    | '/_app/customers/$customerId'
    | '/_app/orders/$orderId'
    | '/_app/orders/new'
    | '/_app/orders/print-batch'
    | '/_app/products/$productId'
    | '/_app/inquiries/'
    | '/_app/orders/'
    | '/_app/products/'
    | '/_app/orders/$orderId/invoice'
    | '/_app/orders/$orderId/waybill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  OrderSlugRoute: typeof OrderSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$slug': {
      id: '/order/$slug'
      path: '/order/$slug'
      fullPath: '/order/$slug'
      preLoaderRoute: typeof OrderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inquiries/': {
      id: '/_app/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof AppInquiriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/print-batch': {
      id: '/_app/orders/print-batch'
      path: '/orders/print-batch'
      fullPath: '/orders/print-batch'
      preLoaderRoute: typeof AppOrdersPrintBatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/orders/$orderId/waybill': {
      id: '/_app/orders/$orderId/waybill'
      path: '/waybill'
      fullPath: '/orders/$orderId/waybill'
      preLoaderRoute: typeof AppOrdersOrderIdWaybillRouteImport
      parentRoute: typeof AppOrdersOrderIdRoute
    }
    '/_app/orders/$orderId/invoice': {
      id: '/_app/orders/$orderId/invoice'
      path: '/invoice'
      fullPath: '/orders/$orderId/invoice'
      preLoaderRoute: typeof AppOrdersOrderIdInvoiceRouteImport
      parentRoute: typeof AppOrdersOrderIdRoute
    }
  }
}

interface AppCustomersRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppOrdersOrderIdRouteChildren {
  AppOrdersOrderIdInvoiceRoute: typeof AppOrdersOrderIdInvoiceRoute
  AppOrdersOrderIdWaybillRoute: typeof AppOrdersOrderIdWaybillRoute
}

const AppOrdersOrderIdRouteChildren: AppOrdersOrderIdRouteChildren = {
  AppOrdersOrderIdInvoiceRoute: AppOrdersOrderIdInvoiceRoute,
  AppOrdersOrderIdWaybillRoute: AppOrdersOrderIdWaybillRoute,
}

const AppOrdersOrderIdRouteWithChildren =
  AppOrdersOrderIdRoute._addFileChildren(AppOrdersOrderIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRouteWithChildren
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppOrdersPrintBatchRoute: typeof AppOrdersPrintBatchRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppInquiriesIndexRoute: typeof AppInquiriesIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRouteWithChildren,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppOrdersPrintBatchRoute: AppOrdersPrintBatchRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppInquiriesIndexRoute: AppInquiriesIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  OrderSlugRoute: OrderSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
