/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders.index'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders.new'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app/orders.$orderId'
import { Route as AppOrdersOrderIdWaybillRouteImport } from './routes/_app/orders.$orderId.waybill'
import { Route as AppOrdersOrderIdInvoiceRouteImport } from './routes/_app/orders.$orderId.invoice'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdWaybillRoute = AppOrdersOrderIdWaybillRouteImport.update({
  id: '/waybill',
  path: '/waybill',
  getParentRoute: () => AppOrdersOrderIdRoute,
} as any)
const AppOrdersOrderIdInvoiceRoute = AppOrdersOrderIdInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AppOrdersOrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRouteWithChildren
  '/orders/new': typeof AppOrdersNewRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/orders/$orderId/invoice': typeof AppOrdersOrderIdInvoiceRoute
  '/orders/$orderId/waybill': typeof AppOrdersOrderIdWaybillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRouteWithChildren
  '/orders/new': typeof AppOrdersNewRoute
  '/orders': typeof AppOrdersIndexRoute
  '/orders/$orderId/invoice': typeof AppOrdersOrderIdInvoiceRoute
  '/orders/$orderId/waybill': typeof AppOrdersOrderIdWaybillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRouteWithChildren
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/orders/$orderId/invoice': typeof AppOrdersOrderIdInvoiceRoute
  '/_app/orders/$orderId/waybill': typeof AppOrdersOrderIdWaybillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/reports'
    | '/settings'
    | '/orders/$orderId'
    | '/orders/new'
    | '/orders/'
    | '/orders/$orderId/invoice'
    | '/orders/$orderId/waybill'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/reports'
    | '/settings'
    | '/orders/$orderId'
    | '/orders/new'
    | '/orders'
    | '/orders/$orderId/invoice'
    | '/orders/$orderId/waybill'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/admin'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/products'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/orders/$orderId'
    | '/_app/orders/new'
    | '/_app/orders/'
    | '/_app/orders/$orderId/invoice'
    | '/_app/orders/$orderId/waybill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId/waybill': {
      id: '/_app/orders/$orderId/waybill'
      path: '/waybill'
      fullPath: '/orders/$orderId/waybill'
      preLoaderRoute: typeof AppOrdersOrderIdWaybillRouteImport
      parentRoute: typeof AppOrdersOrderIdRoute
    }
    '/_app/orders/$orderId/invoice': {
      id: '/_app/orders/$orderId/invoice'
      path: '/invoice'
      fullPath: '/orders/$orderId/invoice'
      preLoaderRoute: typeof AppOrdersOrderIdInvoiceRouteImport
      parentRoute: typeof AppOrdersOrderIdRoute
    }
  }
}

interface AppOrdersOrderIdRouteChildren {
  AppOrdersOrderIdInvoiceRoute: typeof AppOrdersOrderIdInvoiceRoute
  AppOrdersOrderIdWaybillRoute: typeof AppOrdersOrderIdWaybillRoute
}

const AppOrdersOrderIdRouteChildren: AppOrdersOrderIdRouteChildren = {
  AppOrdersOrderIdInvoiceRoute: AppOrdersOrderIdInvoiceRoute,
  AppOrdersOrderIdWaybillRoute: AppOrdersOrderIdWaybillRoute,
}

const AppOrdersOrderIdRouteWithChildren =
  AppOrdersOrderIdRoute._addFileChildren(AppOrdersOrderIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRouteWithChildren
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProductsRoute: AppProductsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRouteWithChildren,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
